### PR TITLE
Connection related metrics added

### PR DESCRIPTION
**Pull request by r0goyal**
This PR aims at adding `Meter` for connection related lifecycle events. This helps in instrumenting connection failure rates

### CODE REVIEW

**Comment by r0goyal** [comment]
@raskasa Have added few connection related metrics for the raw client. Requesting your review for the same.

**Comment by raskasa** [comment]
Thanks.  I'll carve out some time over the next couple of days to take a look at this.  I need to do some project cleanup.

**Comment by raskasa** [comment]
>  I need to do some project cleanup.

I'll take a few more days to finish cleanup.

**Review by raskasa — APPROVED** [review]

**Comment by raskasa** [comment]
@r0goyal I refactored the usage of the EventListener API to better fit how I'd approach things.  See #74 for more specifics.  I'm likely going to stick with my preferred approach, but feel free to provide feedback you have on that refactor directly in that PR.

**Pull request merged**
